# permissions for end users to edit rulers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ruler-editor-role
rules:
- apiGroups:
  - gc.markruler.com
  resources:
  - rulers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gc.markruler.com
  resources:
  - rulers/status
  verbs:
  - get
