# permissions for end users to view rulers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ruler-viewer-role
rules:
- apiGroups:
  - gc.markruler.com
  resources:
  - rulers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gc.markruler.com
  resources:
  - rulers/status
  verbs:
  - get
