apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: crawler
  labels:
    app: crawler
spec:
  schedule: "0 * * * *" # hourly (https://crontab.guru/)
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: crawler
              image: 192.168.7.191:5000/crawler:0.1.0
              imagePullPolicy: Always
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
